spring.application.name=hisabpro-backend

# PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/hisabpro
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

#Short Time Test Expiration
#jwt.access-token-expiration=60000
#jwt.refresh-token-expiration=300000


# Server
server.port=8080